#!/usr/bin/env python3
"""Generate dependency-free TypeScript contracts from the local FastAPI OpenAPI schema."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
BACKEND_ROOT = REPO_ROOT / "backend"
OUTPUT = REPO_ROOT / "frontend" / "src" / "generated" / "api-types.ts"
HEADER = "// Generated by scripts/generate-api-types.py. DO NOT EDIT.\n\n"


def build_openapi() -> dict[str, Any]:
    sys.path.insert(0, str(BACKEND_ROOT))
    from app.config import Settings
    from app.main import create_app

    settings = Settings(
        _env_file=None,
        auth_secret="test-openapi-secret-value-with-32-chars-minimum",
        database_url="postgresql+asyncpg://badi_test:badi_test@127.0.0.1:55433/badi_test",
        environment="test",
        allowed_origins=["http://127.0.0.1:8080"],
    )
    app = create_app(settings)
    return app.openapi()


def schema_name(name: str) -> str:
    safe = "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in name)
    if not safe or safe[0].isdigit():
        safe = f"Schema_{safe}"
    return safe


def literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def ts_type(schema: dict[str, Any] | bool, components: dict[str, Any]) -> str:
    if schema is True:
        return "unknown"
    if schema is False:
        return "never"
    if not isinstance(schema, dict):
        raise TypeError(f"unsupported schema node: {schema!r}")

    if "$ref" in schema:
        ref = str(schema["$ref"])
        prefix = "#/components/schemas/"
        if not ref.startswith(prefix):
            raise ValueError(f"unsupported ref {ref}")
        return schema_name(ref.removeprefix(prefix))

    if "const" in schema:
        return literal(schema["const"])

    if "enum" in schema:
        values = schema["enum"]
        if not isinstance(values, list):
            raise ValueError(f"unsupported enum {values!r}")
        return " | ".join(literal(value) for value in values) or "never"

    unions: list[str] = []
    for key in ("anyOf", "oneOf"):
        if key in schema:
            entries = schema[key]
            if not isinstance(entries, list):
                raise ValueError(f"unsupported {key} {entries!r}")
            unions.extend(ts_type(entry, components) for entry in entries)
    if unions:
        return " | ".join(unions)

    if "allOf" in schema:
        entries = schema["allOf"]
        if not isinstance(entries, list):
            raise ValueError(f"unsupported allOf {entries!r}")
        return " & ".join(ts_type(entry, components) for entry in entries)

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(ts_type({**schema, "type": item}, components) for item in schema_type)

    if not schema or set(schema).issubset({"title", "description", "default", "examples"}):
        return "unknown"

    if schema_type in {"string", None}:
        if schema.get("format") == "binary":
            return "Blob"
        if (
            schema_type == "string"
            or "format" in schema
            or "minLength" in schema
            or "maxLength" in schema
        ):
            return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        items = schema.get("items")
        if items is None:
            raise ValueError("array schema missing items")
        item_type = ts_type(items, components)
        return f"Array<{item_type}>"
    if schema_type == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        if not isinstance(properties, dict):
            raise ValueError(f"unsupported properties {properties!r}")
        required = set(schema.get("required", []))
        lines = ["{"]
        for prop_name, prop_schema in sorted(properties.items()):
            optional = "" if prop_name in required else "?"
            lines.append(f"  {literal(prop_name)}{optional}: {ts_type(prop_schema, components)};")
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            lines.append(f"  [key: string]: {ts_type(additional, components)};")
        elif additional is True:
            lines.append("  [key: string]: unknown;")
        elif additional not in (None, False):
            raise ValueError(f"unsupported additionalProperties {additional!r}")
        lines.append("}")
        return "\n".join(lines)

    raise ValueError(f"unsupported schema: {schema!r}")


def render(openapi: dict[str, Any]) -> str:
    schemas = openapi.get("components", {}).get("schemas", {})
    if not isinstance(schemas, dict):
        raise ValueError("OpenAPI components.schemas missing or invalid")
    chunks = [HEADER]
    for raw_name, schema in sorted(schemas.items()):
        if not isinstance(schema, dict):
            raise ValueError(f"schema {raw_name} is not an object")
        chunks.append(f"export type {schema_name(raw_name)} = {ts_type(schema, schemas)};\n")
    return "\n".join(chunks)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated output is stale")
    args = parser.parse_args()

    output = render(build_openapi())
    if args.check:
        existing = OUTPUT.read_text() if OUTPUT.exists() else ""
        if existing != output:
            print(f"{OUTPUT} is out of date; run scripts/generate-api-types.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(output)
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
